// Versículos del libro de Proverbios — Reina-Valera 1909 (dominio público).
// Selección curada de los proverbios más memorables y aplicables.
// Se elige uno al azar cada vez que se entra al Dashboard.

export type Proverb = {
  /** Cita, p. ej. "Proverbios 3:5" */
  ref: string
  /** Texto del versículo */
  text: string
}

export const PROVERBS: Proverb[] = [
  { ref: "Proverbios 1:7", text: "El principio de la sabiduría es el temor de Jehová; los insensatos desprecian la sabiduría y la enseñanza." },
  { ref: "Proverbios 3:5", text: "Fíate de Jehová de todo tu corazón, y no estribes en tu propia prudencia." },
  { ref: "Proverbios 3:6", text: "Reconócelo en todos tus caminos, y él enderezará tus veredas." },
  { ref: "Proverbios 3:7", text: "No seas sabio en tu propia opinión; teme á Jehová, y apártate del mal." },
  { ref: "Proverbios 3:9", text: "Honra á Jehová con tu sustancia, y con las primicias de todos tus frutos." },
  { ref: "Proverbios 3:11", text: "No deseches, hijo mío, el castigo de Jehová; ni te fatigues de su corrección." },
  { ref: "Proverbios 3:12", text: "Porque Jehová al que ama castiga, como el padre al hijo á quien quiere." },
  { ref: "Proverbios 3:13", text: "Bienaventurado el hombre que halla la sabiduría, y que obtiene la inteligencia." },
  { ref: "Proverbios 3:27", text: "No detengas el bien de sus dueños, cuando tuvieres poder para hacerlo." },
  { ref: "Proverbios 4:7", text: "Sabiduría ante todo: adquiere sabiduría; y ante toda tu posesión adquiere inteligencia." },
  { ref: "Proverbios 4:23", text: "Sobre toda cosa guardada guarda tu corazón; porque de él mana la vida." },
  { ref: "Proverbios 6:6", text: "Ve á la hormiga, oh perezoso; mira sus caminos, y sé sabio." },
  { ref: "Proverbios 6:9", text: "Perezoso, ¿hasta cuándo has de dormir? ¿Cuándo te levantarás de tu sueño?" },
  { ref: "Proverbios 9:9", text: "Da al sabio, y será más sabio; enseña al justo, y acrecerá su saber." },
  { ref: "Proverbios 9:10", text: "El temor de Jehová es el principio de la sabiduría; y la ciencia de los santos es inteligencia." },
  { ref: "Proverbios 10:4", text: "La mano negligente hace pobre; mas la mano de los diligentes enriquece." },
  { ref: "Proverbios 10:9", text: "El que camina en integridad, anda confiado; mas el que pervierte sus caminos, será quebrantado." },
  { ref: "Proverbios 10:12", text: "El odio despierta rencillas; mas la caridad cubre todas las faltas." },
  { ref: "Proverbios 10:19", text: "En las muchas palabras no falta pecado; mas el que refrena sus labios es prudente." },
  { ref: "Proverbios 11:2", text: "Cuando viene la soberbia, viene también la deshonra; mas con los humildes está la sabiduría." },
  { ref: "Proverbios 11:14", text: "Cuando faltan las direcciones, el pueblo cae; mas en la multitud de consejeros hay salud." },
  { ref: "Proverbios 11:25", text: "El alma liberal será engordada; y el que saciare, él también será saciado." },
  { ref: "Proverbios 12:1", text: "El que ama la corrección ama la sabiduría; mas el que aborrece la reprensión, es ignorante." },
  { ref: "Proverbios 12:15", text: "El camino del necio es derecho en su opinión; mas el que obedece al consejo es sabio." },
  { ref: "Proverbios 12:24", text: "La mano de los diligentes se enseñoreará; mas la negligente será tributaria." },
  { ref: "Proverbios 12:25", text: "El cuidado congojoso en el corazón del hombre lo abate; mas la buena palabra lo alegra." },
  { ref: "Proverbios 13:3", text: "El que guarda su boca guarda su alma; mas el que mucho abre sus labios tendrá calamidad." },
  { ref: "Proverbios 13:4", text: "Desea, y nada alcanza el alma del perezoso; mas el alma de los diligentes será engordada." },
  { ref: "Proverbios 13:11", text: "Las riquezas de vanidad disminuirán; pero el que allega con su mano, multiplicará." },
  { ref: "Proverbios 13:20", text: "El que anda con los sabios, sabio será; mas el que se allega á los necios, será quebrantado." },
  { ref: "Proverbios 14:23", text: "En toda labor hay fruto; mas la palabra de los labios solamente empobrece." },
  { ref: "Proverbios 14:29", text: "El que tarda en airarse es grande de entendimiento; mas el corto de espíritu engrandece el desatino." },
  { ref: "Proverbios 15:1", text: "La blanda respuesta quita la ira; mas la palabra áspera hace subir el furor." },
  { ref: "Proverbios 15:13", text: "El corazón alegre hermosea el rostro; mas por el dolor de corazón el espíritu se abate." },
  { ref: "Proverbios 15:22", text: "Los pensamientos son frustrados donde no hay consejo; mas en la multitud de consejeros se afirman." },
  { ref: "Proverbios 15:33", text: "El temor de Jehová es enseñanza de sabiduría; y delante de la honra está la humildad." },
  { ref: "Proverbios 16:3", text: "Encomienda á Jehová tus obras, y tus pensamientos serán afirmados." },
  { ref: "Proverbios 16:9", text: "El corazón del hombre piensa su camino; mas Jehová endereza sus pasos." },
  { ref: "Proverbios 16:18", text: "Antes del quebrantamiento es la soberbia; y antes de la caída la altivez de espíritu." },
  { ref: "Proverbios 16:24", text: "Panal de miel son los dichos suaves; suavidad al alma y medicina á los huesos." },
  { ref: "Proverbios 16:32", text: "Mejor es el que tarda en airarse que el fuerte; y el que se enseñorea de su espíritu, que el que toma una ciudad." },
  { ref: "Proverbios 17:1", text: "Mejor es un bocado seco, y en paz, que la casa de contienda llena de víctimas." },
  { ref: "Proverbios 17:17", text: "En todo tiempo ama el amigo; y el hermano para la angustia es nacido." },
  { ref: "Proverbios 17:22", text: "El corazón alegre produce buena disposición; mas el espíritu triste seca los huesos." },
  { ref: "Proverbios 17:27", text: "Detiene sus dichos el que tiene sabiduría; de prudente espíritu es el hombre entendido." },
  { ref: "Proverbios 18:10", text: "Torre fuerte es el nombre de Jehová; á él correrá el justo, y será levantado." },
  { ref: "Proverbios 18:13", text: "El que responde palabra antes de oir, le es fatuidad y oprobio." },
  { ref: "Proverbios 18:15", text: "El corazón del entendido adquiere sabiduría; y el oído de los sabios busca la ciencia." },
  { ref: "Proverbios 19:11", text: "La cordura del hombre detiene su furor; y su honra es disimular la ofensa." },
  { ref: "Proverbios 19:20", text: "Escucha el consejo, y recibe la corrección, para que seas sabio en tu vejez." },
  { ref: "Proverbios 19:21", text: "Muchos pensamientos hay en el corazón del hombre; mas el consejo de Jehová permanecerá." },
  { ref: "Proverbios 20:4", text: "El perezoso no ara á causa del invierno; pedirá pues en la siega, y no hallará." },
  { ref: "Proverbios 20:11", text: "Aun el muchacho es conocido por sus hechos, si su obra fuere limpia y recta." },
  { ref: "Proverbios 21:5", text: "Los pensamientos del solícito ciertamente van á abundancia; mas todo presuroso, indefectiblemente á pobreza." },
  { ref: "Proverbios 21:23", text: "El que guarda su boca y su lengua, su alma guarda de angustias." },
  { ref: "Proverbios 22:1", text: "De más estima es la buena fama que las muchas riquezas; y la buena gracia más que la plata y el oro." },
  { ref: "Proverbios 22:6", text: "Instruye al niño en su carrera; aun cuando fuere viejo no se apartará de ella." },
  { ref: "Proverbios 22:29", text: "¿Has visto hombre solícito en su obra? delante de los reyes estará; no estará delante de los de baja suerte." },
  { ref: "Proverbios 23:12", text: "Aplica tu corazón á la enseñanza, y tus oídos á las palabras de sabiduría." },
  { ref: "Proverbios 24:10", text: "Si fueres flojo en el día de trabajo, tu fuerza será reducida." },
  { ref: "Proverbios 24:16", text: "Porque siete veces cae el justo, y se torna á levantar; mas los impíos caerán en el mal." },
  { ref: "Proverbios 24:27", text: "Apresta tu obra de afuera, y disponla en tu heredad; y después edificarás tu casa." },
  { ref: "Proverbios 25:11", text: "Manzana de oro con figuras de plata es la palabra dicha como conviene." },
  { ref: "Proverbios 25:28", text: "Como ciudad derribada y sin muro, es el hombre cuyo espíritu no tiene rienda." },
  { ref: "Proverbios 27:1", text: "No te jactes del día de mañana; porque no sabes qué dará de sí el día." },
  { ref: "Proverbios 27:2", text: "Alábete el extraño, y no tu boca; el ajeno, y no tus labios." },
  { ref: "Proverbios 27:17", text: "Hierro con hierro se aguza; y el hombre aguza el rostro de su amigo." },
  { ref: "Proverbios 27:23", text: "Considera atentamente el aspecto de tus ovejas; pon tu corazón á tus rebaños." },
  { ref: "Proverbios 28:1", text: "Huye el impío sin que nadie lo persiga; mas el justo está confiado como un leoncillo." },
  { ref: "Proverbios 28:13", text: "El que encubre sus pecados, no prosperará; mas el que los confiesa y se aparta, alcanzará misericordia." },
  { ref: "Proverbios 28:19", text: "El que labra su tierra, se hartará de pan; mas el que sigue los ociosos, se hartará de pobreza." },
  { ref: "Proverbios 29:11", text: "El necio da suelta á todo su espíritu; mas el sabio al fin le sosiega." },
  { ref: "Proverbios 29:23", text: "La soberbia del hombre le abate; pero al humilde de espíritu sustenta la honra." },
  { ref: "Proverbios 29:25", text: "El temor del hombre pondrá lazo; mas el que confía en Jehová será levantado." },
]
